/* data-apps.js — source of truth for app objects */
"use strict";
var DT = "https://dinaelahl.github.io/desktop-tutorial";

window.PW_APPS = [
  { id: "path-builder", name: "Path Builder", icon: "\ud83e\udded", category: "planning", status: "live",
    desc: "Visual builder to drag, connect, and sequence apps and resources into a structured learning path.",
    features: ["E\u00b2 5-part blueprint", "Drag & drop nodes", "Save & share paths", "LTI 1.3 launch"],
    tags: ["e2", "planning", "flagship"],
    relatedFrameworks: ["e2", "lti13"], relatedResources: ["e2-guide", "e2-template"],
    url: "path-builder.html",
    demoSteps: ["Choose a subject and curriculum", "Select frameworks and apps", "Arrange into a path", "Export or share"] },

  { id: "e2-lesson-planner", name: "E\u00b2 Lesson Planner", icon: "\ud83d\udcdd", category: "planning", status: "live",
    desc: "Generates a complete 5-part blueprint (Hook \u2192 Teach \u2192 Practice \u2192 Connect \u2192 Reflect) with differentiation tiers.",
    features: ["E\u00b2 blueprint", "Differentiation tiers", "PDF / Google Docs export", "Bloom\u2019s alignment"],
    tags: ["planning", "e2", "ai", "flagship"],
    relatedFrameworks: ["e2", "blooms-taxonomy", "udl3"], relatedResources: ["e2-template", "e2-guide"],
    url: DT + "/e2-lesson-planner.html",
    demoSteps: ["Enter topic and grade", "AI generates 5-part plan", "Adjust tiers and levers", "Export PDF"] },

  { id: "e2-blueprint-planner", name: "E\u00b2 Blueprint Planner", icon: "\ud83d\uddfa\ufe0f", category: "planning", status: "live",
    desc: "Stack multiple E\u00b2 lessons into a coherent week, term, or year. Surfaces gaps in modalities and Bloom\u2019s coverage.",
    features: ["Multi-lesson view", "Bloom heatmap", "Modality balance", "Term-level export"],
    tags: ["planning", "e2", "flagship"],
    relatedFrameworks: ["e2", "blooms-taxonomy"], relatedResources: ["e2-guide"],
    url: DT + "/e2-blueprint-planner.html",
    demoSteps: ["Import or create lessons", "View coverage heatmap", "Rebalance modalities", "Export term plan"] },

  { id: "e2-rubrics-assessment", name: "E\u00b2 Rubrics & Assessment", icon: "\ud83d\udcca", category: "assessment", status: "live",
    desc: "Build E\u00b2-aligned rubrics and formative assessments with QTI export and tiered task templates.",
    features: ["QTI 2.2 / 3.0 export", "Holistic & analytic", "Standard alignment", "Tiered task templates"],
    tags: ["assessment", "rubric", "qti", "e2", "flagship"],
    relatedFrameworks: ["e2", "blooms-taxonomy"], relatedResources: ["bloom-matrix", "pbl-rubric"],
    url: DT + "/e2-rubrics-assessment.html",
    demoSteps: ["Choose rubric type", "Add criteria and levels", "Align to standards", "Export QTI"] },

  { id: "flip-studio", name: "FlipStudio", icon: "\ud83c\udfac", category: "engagement", status: "live",
    desc: "Paste any YouTube, website, or PDF link and get a structured flipped lesson with comprehension questions.",
    features: ["Auto-transcription", "Quiz generation", "Timestamp markers", "Accessibility captions"],
    tags: ["video", "flipped", "ai"],
    relatedFrameworks: ["e2", "udl3"], relatedResources: ["flipped-video"],
    url: "#",
    demoSteps: ["Paste a video URL", "AI generates questions", "Add timestamp markers", "Publish to LMS"] },

  { id: "quiz-forge", name: "QuizForge", icon: "\u2753", category: "assessment", status: "live",
    desc: "Generate quizzes from any text, URL, or document. Multiple question types, auto-grading, xAPI reporting.",
    features: ["10 question types", "xAPI reporting", "AI generation", "Adaptive difficulty"],
    tags: ["quiz", "assessment", "ai", "xapi"],
    relatedFrameworks: ["blooms-taxonomy", "xapi", "lti13"], relatedResources: ["bloom-matrix", "xapi-intro"],
    url: "#",
    demoSteps: ["Upload or paste content", "AI generates questions", "Review and edit", "Publish and track"] },

  { id: "differentiate-it", name: "DifferentiateIt", icon: "\ud83c\udfaf", category: "planning", status: "live",
    desc: "Paste any task \u2192 get three auto-differentiated versions (struggling, on-level, advanced).",
    features: ["3 tiers auto-generated", "UDL-aligned", "Reading level adjustment", "Vocabulary scaffolding"],
    tags: ["differentiation", "udl", "accessibility"],
    relatedFrameworks: ["udl3", "e2"], relatedResources: ["diff-menu", "udl-cheat"],
    url: "#",
    demoSteps: ["Paste original task", "AI generates 3 tiers", "Adjust reading levels", "Copy or export"] },

  { id: "exit-ticket", name: "ExitTicket", icon: "\ud83d\udeaa", category: "assessment", status: "live",
    desc: "Quick formative check-ins that surface understanding in real time. 60-second polls and open-ended prompts.",
    features: ["Real-time results", "10 prompt types", "Class analytics", "Anonymous mode"],
    tags: ["assessment", "formative", "engagement"],
    relatedFrameworks: ["e2", "xapi", "lti13"], relatedResources: ["exit-bank"],
    url: "#",
    demoSteps: ["Choose prompt type", "Students respond on any device", "View live results", "Export data"] },

  { id: "vocab-vault", name: "VocabVault", icon: "\ud83d\udcda", category: "languages", status: "live",
    desc: "Spaced-repetition vocabulary sets for any subject. CEFR-tagged for language classes.",
    features: ["SM-2 algorithm", "CEFR tagging", "Audio pronunciation", "Image association"],
    tags: ["vocabulary", "spaced-rep", "languages", "cefr"],
    relatedFrameworks: ["cefr-arabic"], relatedResources: ["arabic-cefr"],
    url: "#",
    demoSteps: ["Upload word list or generate from topic", "Tag CEFR levels", "Students drill via SR", "Track mastery"] },

  { id: "hifz-helper", name: "HifzHelper", icon: "\ud83d\udcff", category: "arabic", status: "live",
    desc: "Quran memorisation tracker with mutashabihat hints, murajaah cycles, and ijazah teacher linking.",
    features: ["Mutashabihat alerts", "Murajaah scheduler", "Tajweed notes", "Progress charts"],
    tags: ["quran", "hifz", "arabic", "islamic"],
    relatedFrameworks: ["cefr-arabic"], relatedResources: ["hifz-tracker", "tajweed-rules"],
    url: "#",
    demoSteps: ["Select surah and juz", "Set daily target", "Record and review", "Track with charts"] },

  { id: "arabic-lab", name: "ArabicLab", icon: "\u0639", category: "arabic", status: "live",
    desc: "Arabic as a second language studio with CEFR A1\u2013C2 tracks, Fusha vs dialect switching.",
    features: ["CEFR A1\u2013C2", "Fusha & dialect", "Grammar drills", "Speaking practice"],
    tags: ["arabic", "language", "cefr", "asl"],
    relatedFrameworks: ["cefr-arabic"], relatedResources: ["arabic-cefr"],
    url: "#",
    demoSteps: ["Take placement test", "Choose Fusha or dialect track", "Complete daily drills", "Track CEFR progress"] },

  { id: "project-pilot", name: "ProjectPilot", icon: "\ud83d\ude80", category: "pbl", status: "beta",
    desc: "Full PBL project planner with timeline, collaboration tools, and a driving-question builder.",
    features: ["Driving question builder", "Milestone tracker", "Peer collaboration", "Exhibition planner"],
    tags: ["pbl", "project", "collaboration"],
    relatedFrameworks: ["e2"], relatedResources: ["pbl-rubric"],
    url: "#",
    demoSteps: ["Write driving question", "Set milestones", "Assign team roles", "Plan exhibition"] },

  { id: "timeline-pro", name: "TimelinePro", icon: "\ud83d\udcc5", category: "engagement", status: "beta",
    desc: "Visual history and sequence timeline builder. Drag events, add images and sources.",
    features: ["Drag & drop events", "Image embeds", "Source citations", "Interactive publish"],
    tags: ["history", "visual", "social-studies"],
    relatedFrameworks: ["blooms-taxonomy"], relatedResources: [],
    url: "#",
    demoSteps: ["Create timeline", "Add events with dates", "Attach images and sources", "Publish interactive view"] },

  { id: "data-dash", name: "DataDash", icon: "\ud83d\udcc8", category: "assessment", status: "beta",
    desc: "Student progress analytics across all Pathways apps. Early warning alerts and parent-friendly reports.",
    features: ["Cross-app analytics", "Early warning alerts", "Parent reports", "Bloom\u2019s distribution"],
    tags: ["analytics", "data", "reporting"],
    relatedFrameworks: ["xapi", "ferpa", "gdpr-k"], relatedResources: ["xapi-intro", "ferpa"],
    url: "#",
    demoSteps: ["Connect apps via xAPI", "View class dashboard", "Set alert thresholds", "Generate reports"] },

  { id: "read-aloud", name: "ReadAloud Studio", icon: "\ud83d\udd0a", category: "languages", status: "soon",
    desc: "Text-to-speech studio with natural Arabic and English voices. Exports MP3 or embeds inline.",
    features: ["Arabic TTS", "English TTS", "SSML support", "Accessibility export"],
    tags: ["accessibility", "udl", "languages"],
    relatedFrameworks: ["wcag22", "udl3", "cefr-arabic"], relatedResources: [],
    url: "#",
    demoSteps: ["Paste or upload text", "Choose voice and language", "Preview audio", "Export MP3 or embed"] }
];
